# Generated by Django 5.2.6 on 2025-10-30 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6c5ce7', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium_only', models.BooleanField(default=False, help_text='Only available to premium users')),
                ('preview_duration', models.PositiveIntegerField(default=30, help_text='Preview duration in seconds for free users')),
                ('audio_quality', models.CharField(choices=[('standard', 'Standard'), ('high', 'High (320kbps)'), ('ultra', 'Ultra HD (FLAC)')], default='standard', max_length=20)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('bpm', models.PositiveIntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artists.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.genre')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='SongDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_offline_download', models.BooleanField(default=False)),
                ('audio_quality', models.CharField(choices=[('standard', 'Standard'), ('high', 'High (320kbps)'), ('ultra', 'Ultra HD (FLAC)')], default='standard', max_length=20)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='music.song')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SongPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('duration_played', models.PositiveIntegerField(default=0, help_text='Seconds played')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_quality', models.CharField(choices=[('standard', 'Standard'), ('high', 'High (320kbps)'), ('ultra', 'Ultra HD (FLAC)')], default='standard', max_length=20)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='music.song')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-upload_date'], name='music_song_upload__14d0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_approved', 'is_featured'], name='music_song_is_appr_f14b65_idx'),
        ),
        migrations.AddIndex(
            model_name='songdownload',
            index=models.Index(fields=['-downloaded_at'], name='music_songd_downloa_c9ecec_idx'),
        ),
        migrations.AddIndex(
            model_name='songdownload',
            index=models.Index(fields=['song', 'downloaded_at'], name='music_songd_song_id_b9085d_idx'),
        ),
        migrations.AddIndex(
            model_name='songplay',
            index=models.Index(fields=['-played_at'], name='music_songp_played__53e08d_idx'),
        ),
        migrations.AddIndex(
            model_name='songplay',
            index=models.Index(fields=['song', 'played_at'], name='music_songp_song_id_d86061_idx'),
        ),
    ]
