# Generated by Django 5.2.6 on 2025-10-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_album_song_lyrics_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
