# Generated by Django 5.2.6 on 2025-10-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
