# Generated by Django 5.2.6 on 2025-10-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_album_remove_song_lyrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
