# Generated by Django 5.2.6 on 2025-11-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_newsarticle_views_newscomment_newsview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['-added_date']},
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
