# Generated by Django 5.2.6 on 2025-10-10 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_album_song_lyrics_alter_song_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('premium_plus', 'Premium Plus')], max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_premium_curated',
            field=models.BooleanField(default=False, help_text='Premium-only curated playlist'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_premium_only',
            field=models.BooleanField(default=False, help_text='Only available to premium users'),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_duration',
            field=models.PositiveIntegerField(default=30, help_text='Preview duration in seconds for free users'),
        ),
        migrations.AddField(
            model_name='songdownload',
            name='audio_quality',
            field=models.CharField(choices=[('standard', 'Standard'), ('high', 'High'), ('ultra', 'Ultra HD')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='songdownload',
            name='is_offline_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='songplay',
            name='audio_quality',
            field=models.CharField(choices=[('standard', 'Standard'), ('high', 'High'), ('ultra', 'Ultra HD')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_offline_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='offline_downloads_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('premium_plus', 'Premium Plus')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
