# Generated by Django 5.2.6 on 2025-10-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_subscriptionplan_remove_song_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_premium_curated',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_premium_only',
        ),
        migrations.RemoveField(
            model_name='song',
            name='preview_duration',
        ),
        migrations.RemoveField(
            model_name='songdownload',
            name='audio_quality',
        ),
        migrations.RemoveField(
            model_name='songdownload',
            name='is_offline_download',
        ),
        migrations.RemoveField(
            model_name='songplay',
            name='audio_quality',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='max_offline_downloads',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='offline_downloads_used',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_expires',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_since',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_subscription_id',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
