# Generated by Django 5.2.6 on 2025-10-31 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user'),
        ('music', '0002_alter_song_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-liked_at'],
                'unique_together': {('user_profile', 'song')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', through='accounts.LikedSong', to='music.song'),
        ),
    ]
